// export const resume = {
//   personalInfo: {
//     name: "Ovodo Ohwovoriole",
//     title: "Senior Full-Stack & Blockchain Developer",
//     phone: "+2349067885409",
//     email: "ohwovoriole@gmail.com",
//     location: "Nigeria",
//     linkedin: "https://www.linkedin.com/in/ovodo",
//     github: "https://www.github.com/ovodo",
//     website: "https://www.tricode.pro",
//   },
//   summary:
//     "Versatile software engineer with 5+ years of expertise in full-stack development and blockchain technologies. Proven ability to rapidly adapt to new tools and frameworks, delivering high-impact solutions that improve efficiency, scalability, and user engagement. Adept at leading cross-functional teams and driving innovation in decentralized applications.",
//   experience: [
//     {
//       title: "Senior Full-Stack Developer",
//       company: "Tricode Pro Ltd",
//       image: "/tricode.png",
//       link: "https://www.tricode.pro",
//       dates: "04/2023 - Present",
//       location: "Lagos, Remote",
//       achievements: [
//         "Spearheaded the development and launch of mobile and web applications using **React**, **React Native**, **Expo**, **MongoDB**, and **Redux**, improving development efficiency and product stability by **20%**.",
//         "Led a team of **10 engineers** to deliver projects on time, enhancing collaboration and increasing user engagement by **25%** through optimized **UI/UX** workflows.",
//         "Built a web-based trading platform using **Python** and **Django**, hosted on **AWS EC2** with **S3** integration, reducing trading overhead costs by **15%** and enabling optimized trade execution.",
//         "Automated dynamic PDF report generation using **ReportLab**, cutting manual effort by **40%** and accelerating client deliverables by **30%**.",
//       ],
//     },
//     {
//       title: "Full-Stack & Blockchain Developer",
//       company: "Stackup",
//       dates: "11/2023 - 01/2025",
//       image: "/stackup.png",
//       link: "https://www.tricode.pro",
//       location: "Remote",
//       achievements: [
//         "Completed **50+ technical learning paths** in **Blockchain Development**, **Smart Contracts**, and **Web3**, achieving a **95% success rate** in assessments.",
//         "Earned **$1000+ in bounties** for high-impact projects, including **NFT marketplaces**, **DeFi** applications, and games on **Aptos**, **Sui**, and **Ethereum** blockchains.",
//       ],
//     },
//     {
//       title: "Senior Front-End Engineer",
//       company: "Lazarus Network",
//       dates: "03/2024 - 05/2024",
//       image: "/lazarus.jpg",
//       link: "https://lazarus.network",
//       location: "Miami, Remote",
//       achievements: [
//         "Developed high-performance user interfaces with **Next.js**, accelerating product launches for **Web3** and Chrome extensions by **20%**.",
//         "Mentored **5 junior engineers**, improving team productivity by **30%** through knowledge-sharing sessions on **UI/UX** principles and code optimization.",
//       ],
//     },
//     {
//       title: "Blockchain Developer",
//       company: "Overmind Network",
//       dates: "08/2023 - 02/2024",
//       location: "Remote",
//       image: "/overmind.png",
//       link: "https://www.tricode.pro",
//       achievements: [
//         "Designed and deployed **15+ advanced smart contracts** for **DeFi**, gaming, and e-commerce applications on **Aptos** and **Sui**, enhancing transaction efficiency by **30%** and reducing security vulnerabilities by **20%**.",
//         "Ranked in the **top 20 out of thousands of developers** on the platform, leveraging the **Move** programming language for scalable decentralized solutions.",
//       ],
//     },
//     {
//       title: "Web Development Facilitator",
//       company: "Project T-MAX",
//       dates: "01/2023 - 03/2023",
//       location: "Benin City, Nigeria",
//       image: "/tmax.png",
//       link: "",
//       achievements: [
//         "Trained **50+ students** in **HTML**, **CSS**, **JavaScript**, **React**, **Node.js**, and **MongoDB**, increasing their development productivity by **25%**.",
//         "Advised on tool adoption, streamlining workflows and reducing project delivery times by **15%**.",
//       ],
//     },
//     {
//       title: "Full-Stack Developer",
//       company: "Neroitech Inventions",
//       dates: "01/2021 - 12/2022",
//       image: "/niti.jpg",
//       link: "https://niti.com.ng",
//       location: "Warri, Nigeria",
//       achievements: [
//         "Designed and implemented user interfaces from **UI designs**, boosting user satisfaction by **20%** through improved usability and aesthetics.",
//         "Built robust database systems integrated with **Google Sheets**, reducing data access errors by **25%**.",
//       ],
//     },
//   ],
//   education: [
//     {
//       title: "Bachelor of Engineering (Mechanical Engineering)",
//       company: "University of Benin",
//       dates: "11/2009 - 11/2014",
//       location: "Benin City, Nigeria",
//       achievements: [],
//       image: "",
//       link: "",
//     },
//   ],
//   certifications: [
//     {
//       title: "Software Engineering Job Simulation",
//       company: "JPMorgan Chase & Co.",
//       dates: "11/10/2023",
//       image: "",
//       location: "",
//       link: "https://resume-six-kappa-53.vercel.app/cert",
//       achievements: [
//         "Gained hands-on experience in software engineering through a simulation at a leading financial institution.",
//       ],
//     },
//   ],
//   achievements: [
//     {
//       title: "Top 20 Blockchain Developer",
//       description:
//         "Ranked among the **top 20 developers** out of thousands on a blockchain platform, demonstrating expertise in **Move** and decentralized application development.",
//     },
//   ],
//   hobbies: [
//     "Playing Musical Instruments",
//     "Listening to Music",
//     "Audio Production",
//     "Watching Movies",
//   ],
//   skills: [
//     "Full-Stack Development",
//     "Blockchain & Web3",
//     "Smart Contracts (Solidity, Move)",
//     "React, Next.js, Redux",
//     "Python, Django, Flask",
//     "JavaScript, TypeScript, Rust",
//     "AWS (EC2, S3), GCP",
//     "MongoDB, PostgreSQL, Redis",
//     "Docker, Git, CI/CD",
//     "UI/UX Design (Figma)",
//     "Agile Methodologies",
//     "Team Leadership & Mentorship",
//   ],
//   projects: [
//     {
//       title: "Lead Developer",
//       company: "Edusoul Distinct",
//       image: "/edusoul.svg",
//       location: "",
//       achievements: [
//         "Built a **Learning Management System (LMS)** with **Role-Based Access Control (RBAC)** and content management, improving administrative efficiency by **20%** and student engagement by **15%**.",
//       ],
//       dates: "",
//       link: "https://www.edusouldistinct.com",
//     },
//     {
//       title: "Lead Developer",
//       company: "Donacare Foundation",
//       image: "/dona.png",
//       location: "",
//       achievements: [
//         "Developed an online platform for an NGO, integrating **Paystack** for seamless donation processing, resulting in a **40% increase in donations** within the first 3 months.",
//       ],
//       dates: "",
//       link: "https://www.donacarefoundation.org",
//     },
//     {
//       title: "Open Source Contributor",
//       company: "Solana Foundation",
//       image: "/solana.jpg",
//       location: "",
//       dates: "11/09/2024",
//       achievements: [
//         "Enhanced escrow and token swap examples using the **Steel** framework and **Rust**, with testing implemented via **Solana** bankrun.js and native **Rust**, improving code reliability by **25%**.",
//         "Improved documentation for Solana Oracles, reducing developer onboarding time by **30%**.",
//       ],
//       link: "https://github.com/Ovodo/program-examples/tree/tokens/escrow/steel/tokens/escrow/steel",
//     },
//   ],
// };
export const resume = {
  personalInfo: {
    name: "Ovodo Ohwovoriole",
    title: "Senior Full-Stack & Blockchain Developer",
    phone: "+2349067885409",
    email: "ohwovoriole@gmail.com",
    location: "Nigeria",
    linkedin: "https://www.linkedin.com/in/ovodo",
    github: "https://www.github.com/ovodo",
    website: "https://www.tricode.pro",
  },
  summary:
    "Versatile software engineer with 5+ years of expertise in full-stack development and blockchain technologies. Proven ability to rapidly adapt to new tools and frameworks, delivering high-impact solutions that improve efficiency, scalability, and user engagement. Adept at leading cross-functional teams and driving innovation in decentralized applications.",
  experience: [
    {
      title: "Senior Full-Stack Developer",
      company: "Tricode Pro Ltd",
      image: "/tricode.png",
      link: "https://www.tricode.pro",
      dates: "04/2023 - Present",
      location: "Lagos, Remote",
      achievements: [
        "Spearheaded the development and launch of mobile and web applications using **React**, **React Native**, **Expo**, **MongoDB**, and **Redux**, improving development efficiency and product stability by **20%**.",
        "Led a team of **10 engineers** to deliver projects on time, enhancing collaboration and increasing user engagement by **25%** through optimized **UI/UX** workflows.",
        "Built a web-based trading platform using **Python** and **Django**, hosted on **AWS EC2** with **S3** integration, reducing trading overhead costs by **15%** and enabling optimized trade execution.",
        "Automated dynamic PDF report generation using **ReportLab**, cutting manual effort by **40%** and accelerating client deliverables by **30%**.",
      ],
    },
    {
      title: "Full-Stack & Blockchain Developer",
      company: "Stackup",
      dates: "11/2023 - 01/2025",
      image: "/stackup.png",
      link: "https://www.tricode.pro",
      location: "Remote",
      achievements: [
        "Completed **50+ technical learning paths** in **Blockchain Development**, **Smart Contracts**, and **Web3**, achieving a **95% success rate** in assessments.",
        "Earned **$1000+ in bounties** for high-impact projects, including **NFT marketplaces**, **DeFi** applications, and games on **Aptos**, **Sui**, and **Ethereum** blockchains.",
      ],
    },
    {
      title: "Senior Front-End Engineer",
      company: "Lazarus Network",
      dates: "03/2024 - 05/2024",
      image: "/lazarus.jpg",
      link: "https://lazarus.network",
      location: "Miami, Remote",
      achievements: [
        "Developed high-performance user interfaces with **Next.js**, accelerating product launches for **Web3** and Chrome extensions by **20%**.",
        "Mentored **5 junior engineers**, improving team productivity by **30%** through knowledge-sharing sessions on **UI/UX** principles and code optimization.",
      ],
    },
    {
      title: "Blockchain Developer",
      company: "Overmind Network",
      dates: "08/2023 - 02/2024",
      location: "Remote",
      image: "/overmind.png",
      link: "https://www.tricode.pro",
      achievements: [
        "Designed and deployed **15+ advanced smart contracts** for **DeFi**, gaming, and e-commerce applications on **Aptos** and **Sui**, enhancing transaction efficiency by **30%** and reducing security vulnerabilities by **20%**.",
        "Ranked in the **top 20 out of thousands of developers** on the platform, leveraging the **Move** programming language for scalable decentralized solutions.",
      ],
    },
    {
      title: "Web Development Facilitator",
      company: "Project T-MAX",
      dates: "01/2023 - 03/2023",
      location: "Benin City, Nigeria",
      image: "/tmax.png",
      link: "",
      achievements: [
        "Trained **50+ students** in **HTML**, **CSS**, **JavaScript**, **React**, **Node.js**, and **MongoDB**, increasing their development productivity by **25%**.",
        "Advised on tool adoption, streamlining workflows and reducing project delivery times by **15%**.",
      ],
    },
    {
      title: "Full-Stack Developer",
      company: "Neroitech Inventions",
      dates: "01/2021 - 12/2022",
      image: "/niti.jpg",
      link: "https://niti.com.ng",
      location: "Warri, Nigeria",
      achievements: [
        "Designed and implemented user interfaces from **UI designs**, boosting user satisfaction by **20%** through improved usability and aesthetics.",
        "Built robust database systems integrated with **Google Sheets**, reducing data access errors by **25%**.",
      ],
    },
  ],
  education: [
    {
      title: "Bachelor of Engineering (Mechanical Engineering)",
      company: "University of Benin",
      dates: "11/2009 - 11/2014",
      location: "Benin City, Nigeria",
      achievements: [],
      image: "",
      link: "",
    },
  ],
  certifications: [
    {
      title: "Software Engineering Job Simulation",
      company: "JPMorgan Chase & Co.",
      dates: "11/10/2023",
      image: "",
      location: "",
      link: "https://resume-six-kappa-53.vercel.app/cert",
      achievements: [
        "Gained hands-on experience in software engineering through a simulation at a leading financial institution.",
      ],
    },
  ],
  achievements: [
    {
      title: "Top 20 Blockchain Developer",
      description:
        "Ranked among the **top 20 developers** out of thousands on a blockchain platform, demonstrating expertise in **Move** and decentralized application development.",
    },
  ],
  hobbies: [
    "Playing Musical Instruments",
    "Listening to Music",
    "Audio Production",
    "Watching Movies",
  ],
  skills: [
    "Full-Stack Development",
    "Blockchain & Web3",
    "Smart Contracts (Solidity, Move)",
    "React, Next.js, Redux",
    "Python, Django, Flask",
    "JavaScript, TypeScript, Rust",
    "AWS (EC2, S3), GCP",
    "MongoDB, PostgreSQL, Redis",
    "Docker, Git, CI/CD",
    "UI/UX Design (Figma)",
    "Agile Methodologies",
    "Team Leadership & Mentorship",
  ],
  projects: [
    {
      title: "Lead Developer",
      company: "Edusoul Distinct",
      image: "/edusoul.svg",
      location: "",
      achievements: [
        "Built a **Learning Management System (LMS)** with **Role-Based Access Control (RBAC)** and content management, improving administrative efficiency by **20%** and student engagement by **15%**.",
      ],
      dates: "",
      link: "https://www.edusouldistinct.com",
    },
    {
      title: "Lead Developer",
      company: "Donacare Foundation",
      image: "/dona.png",
      location: "",
      achievements: [
        "Developed an online platform for an NGO, integrating **Paystack** for seamless donation processing, resulting in a **40% increase in donations** within the first 3 months.",
      ],
      dates: "",
      link: "https://www.donacarefoundation.org",
    },
    {
      title: "Open Source Contributor",
      company: "Solana Foundation",
      image: "/solana.jpg",
      location: "",
      dates: "11/09/2024",
      achievements: [
        "Enhanced escrow and token swap examples using the **Steel** framework and **Rust**, with testing implemented via **Solana** bankrun.js and native **Rust**, improving code reliability by **25%**.",
        "Improved documentation for Solana Oracles, reducing developer onboarding time by **30%**.",
      ],
      link: "https://github.com/Ovodo/program-examples/tree/tokens/escrow/steel/tokens/escrow/steel",
    },
  ],
};
