export const resume = {
    personalInfo: {
        name: "Ovodo Ohwovoriole",
        title: "Senior FrontEnd Developer",
        phone: "+2349067885409",
        email: "ovodo@ovd.dev",
        location: "Nigeria",
        linkedin: "https://www.linkedin.com/in/ovodo",
        github: "https://www.github.com/ovodo",
        website: "https://www.ovd.dev",
    },
    summary:
        "Senior Frontend Engineer with 5+ years building pixel-perfect, accessible web and mobile UIs using React, Next.js, and TypeScript. Strong in frontend architecture, design systems, and performance, leading teams to ship scalable products that improve reliability and engagement.",
    experience: [
        {
            title: "Senior Frontend Engineer",
            company: "Tricode Pro Ltd",
            image: "/tricode.png",
            link: "https://www.tricode.pro",
            dates: "04/2023 - Present",
            location: "Lagos, Remote",
            achievements: [
                "Owned frontend architecture and delivery across multiple products, building scalable, maintainable UIs with **React**, **Next.js**, and **TypeScript** using reusable component patterns and strong state management.",
                "Built a **SaaS project management** platform (tasks, assignments, duty uploads, team workflows), implementing responsive, pixel-perfect UI and integrating **Flutterwave** for subscription/payment flows.",
                "Delivered an **EdTech LMS** with rich content authoring via **TipTap**, using **MongoDB**-backed content workflows; implemented admin tooling for course publishing, assignment submission/review, and grading, plus **Stripe** payments.",
                "Developed the frontend for a decentralized cross-border payments platform (Lockup), integrating **Sui zkLogin** and collaborating on **Move** smart contracts to support secure P2P payment flows.",
                "Architected a hackathon mobile app (Sui Meme) using **React Native**, focusing on clean navigation/state patterns and a polished UX for sharing memes on the **Sui** network.",
            ],
        },
        {
            title: "Full-Stack Blockchain Developer",
            company: "Stackup",
            dates: "11/2023 - 01/2025",
            image: "/stackup.png",
            link: "https://app.stackup.dev",
            location: "Remote",
            achievements: [
                "Built and shipped full-stack **Web3** applications across **EVM** and **L2 (Arbitrum)** networks, implementing wallet connection with **Reown (WalletConnect)**, transaction flows, and contract integrations with **ethers.js**, **web3.js**, and **wagmi**.",
                "Implemented advanced **Redux** patterns (normalized state, memoized selectors, middleware, async orchestration, optimistic updates) to deliver reliable, high-signal dApp UX under real-world network latency.",
                "Designed and deployed an **NFT** on the **Aptos** blockchain (Move), using **IPFS** for asset/metadata storage; recognized for technical execution and end-to-end delivery.",
                "Developed a blockchain adventure game (\"Bounty Hunter\") featuring **ERC20/ERC721** mechanics, on-chain progression logic, and a production-ready frontend integrating Web3 wallets.",
                "Prototyped **AI-assisted** Web3 features using **RAG** workflows (LLM tooling, retrieval, and prompt orchestration) to improve user support and developer productivity.",
            ],
        },
        {
            title: "Senior Front-End Engineer",
            company: "Lazarus Network",
            dates: "03/2024 - 05/2024",
            image: "/lazarus.jpg",
            link: "https://lazarus.network",
            location: "Miami, Remote",
            achievements: [
                "Built pixel-perfect, high-performance user interfaces with **Next.js**, accelerating product launches for **Web3** products and Chrome extensions by **20%**.",
                "Contributed to **Netespio**, a **DePIN** blockchain project, delivering core product features and helping the team win multiple hackathons.",
                "Developed and shipped a **Chrome Extension** using **SvelteKit** and **Chrome Manifest V3**, implementing secure extension architecture, optimized UX flows, and reliable production releases.",
                "Mentored **5 junior engineers**, supporting debugging, performance improvements, and best practices in UI engineering, improving team productivity by **30%**.",
            ],
        },
        {
            title: "Blockchain Developer",
            company: "Overmind Network",
            dates: "08/2023 - 02/2024",
            location: "Remote",
            image: "/overmind.png",
            link: "https://overmind.xyz",
            achievements: [
                "Designed and deployed **15+ advanced smart contracts** for **DeFi**, gaming, and e-commerce applications on **Aptos** and **Sui**, enhancing transaction efficiency by **30%** and reducing security vulnerabilities by **20%**.",
                "Ranked in the **top 20 out of thousands of developers** on the platform, leveraging the **Move** programming language for scalable decentralized solutions.",
            ],
        },
        {
            title: "Web Development Facilitator",
            company: "Project T-MAX",
            dates: "01/2023 - 03/2023",
            location: "Benin City, Nigeria",
            image: "/tmax.png",
            link: "",
            achievements: [
                "Trained **50+ students** in **HTML**, **CSS**, **JavaScript**, **React**, **Node.js**, and **MongoDB**, increasing their development productivity by **25%**.",
                "Advised on tool adoption, streamlining workflows and reducing project delivery times by **15%**.",
            ],
        },
        {
            title: "Full-Stack Blockchain Developer",
            company: "Neroitech Inventions",
            dates: "01/2021 - 12/2022",
            image: "/niti.jpg",
            link: "https://niti.com.ng",
            location: "Warri, Nigeria",
            achievements: [
                "Designed and implemented responsive, pixel-perfect user interfaces from **UI designs**, boosting user satisfaction by **20%** through improved usability and aesthetics.",
                "Built **Bandbindex**, a crypto market insights tool featuring sentiment analysis and custom indexes, delivering actionable analytics for users.",
                "Implemented interactive chart dashboards to visualize index performance and sentiment trends for decision-making.",
                "Created and deployed a token on the **Ethereum** chain and implemented a farming/rewards mechanism to distribute emissions to users on a daily schedule.",
                "Integrated **MetaMask** wallet connection using the **window.ethereum** provider, handling account/network changes and enabling transaction signing.",
                "Built robust database systems integrated with **Google Sheets**, reducing data access errors by **25%**.",
            ],
        },
    ],
    education: [
        {
            title: "Bachelor of Engineering (Mechanical Engineering)",
            company: "University of Benin",
            dates: "11/2009 - 11/2014",
            location: "Benin City, Nigeria",
            achievements: [],
            image: "",
            link: "",
        },
    ],
    certifications: [
        {
            title: "Software Engineering Job Simulation",
            company: "JPMorgan Chase & Co.",
            dates: "11/10/2023",
            image: "",
            location: "",
            link: "https://resume-six-kappa-53.vercel.app/cert",
            achievements: [
                "Gained hands-on experience in software engineering through a simulation at a leading financial institution.",
            ],
        },
    ],
    achievements: [
        {
            title: "Top 20 Blockchain Developer",
            description:
                "Ranked among the **top 20 developers** out of thousands on a blockchain platform, demonstrating expertise in **Move** and decentralized application development.",
        },
    ],
    hobbies: [
        "Playing Musical Instruments",
        "Listening to Music",
        "Audio Production",
        "Watching Movies",
    ],
    skills: [
        "Full-Stack Development",
        "Blockchain & Web3",
        "Smart Contracts (Solidity, Move)",
        "React, Next.js, Redux",
        "Python, Django, Flask",
        "JavaScript, TypeScript, Rust",
        "AWS (EC2, S3), GCP",
        "MongoDB, PostgreSQL, Redis",
        "Docker, Git, CI/CD",
        "UI/UX Design (Figma)",
        "Agile Methodologies",
        "GraphQL",
        "Rust",
        "Anchor",
        "AI Integration",
        "LangChain",
        "RAG Architecture",
        "Vector Databases",
    ],
    projects: [
        {
            title: "Extension Developer",
            company: "MoveWithDizzle",
            image: "/mwd.png",
            location: "",
            achievements: [
                "Developed a **VS Code extension** to enhance developer productivity when writing **Move** smart contracts, integrating **LangChain** for AI-powered code assistance.",
                "Implemented **RAG (Retrieval-Augmented Generation)** architecture with **MongoDB Vector Database** to chunk and store Move language documentation for context-aware code suggestions.",
                "Submitted as a **hackathon project**, showcasing innovative integration of AI tooling with blockchain development workflows.",
            ],
            dates: "",
            link: "",
        },
        {
            title: "Lead Full Stack Blockchain Developer",
            company: "Exyra AI DeFi Assistant",
            image: "/exyra-logo.svg",
            location: "",
            achievements: [
                "Built **Exyra**, a multi-chain AI DeFi assistant with a friendly, accessible conversational UX, enabling users to explore protocols and complete on-chain workflows confidently.",
                "Implemented AI chat experiences using **CopilotKit** with saved prompts, search, and chat history persisted via **MongoDB**.",
                "Delivered multi-chain wallet connectivity using **Reown AppKit (WalletConnect v2)** and contract interaction primitives with **wagmi**, **viem**, and **ethers.js**.",
                "Built protocol and routing experiences across **Ethereum**, **Arbitrum**, **Optimism**, **BSC**, and **Solana**, including explorer flows and real-time market data (token prices, gas estimates).",
                "Implemented secure exchange-key management (Binance/Bybit) with **AES-256-GCM** encryption and wallet-based syncing, plus a rewards/tasks system using **Redux Toolkit**.",
            ],
            dates: "",
            link: "",
            repo: "https://github.com/Exyralabs/FrontEnd",
            summary: "A multi-chain AI DeFi assistant built with Next.js (App Router) and CopilotKit, combining conversational guidance with protocol exploration, wallet connectivity, and real-time market data.",
            languages: ["TypeScript", "JavaScript"],
            keywords: ["AI", "DeFi", "Web3", "Multi-chain", "CopilotKit", "Next.js", "TypeScript", "MongoDB", "Redux Toolkit", "Reown AppKit", "WalletConnect", "wagmi", "viem", "ethers.js"],
            category: ["AI", "Blockchain", "DeFi", "Full-Stack"],
            video: "",
            images: [
                {
                    src: "/exyra-chat.png",
                    title: "AI-Powered Chat Interface"
                },
                {
                    src: "/exyra-explore.png",
                    title: "DeFi Protocol Explorer"
                },
                {
                    src: "/exyra-wallet.png",
                    title: "Multi-Chain Wallet Integration"
                }
            ]
        },
        {
            title: "Full-Stack Blockchain Developer",
            company: "SkyOps",
            image: "/skyops-logo.svg",
            location: "",
            achievements: [
                "Built **SkyOps**, a decentralized GPU compute marketplace (**Next.js**, **TypeScript**).",
                "Implemented wallet + tx flows with **Reown AppKit** (Solana + wagmi adapters), **Solana Web3**, **Anchor**, and **ethers.js**.",
                "Deployed cross-chain **rewards/claim** contracts on **EVM** and **Solana (SVM)**.",
                "Built **Express** + **MongoDB (mongoose)** services integrating **OpenAI** and **HuggingFace**.",
                "Shipped a **Plasmo** (Manifest V3) browser extension with **Redux Toolkit**.",
                "Contributed tooling + analytics with **Foundry** (EVM) and **Next.js** + **Recharts**.",
            ],
            dates: "",
            link: "",
        },
        // {
        //     title: "Lead Developer",
        //     company: "Edusoul Distinct",
        //     image: "/edusoul.svg",
        //     location: "",
        //     achievements: [
        //         "Built a **Learning Management System (LMS)** with **Role-Based Access Control (RBAC)** and content management, improving administrative efficiency by **20%** and student engagement by **15%**.",
        //     ],
        //     dates: "",
        //     link: "https://www.edusouldistinct.com",
        // },
        // {
        //     title: "Lead Developer",
        //     company: "Donacare Foundation",
        //     image: "/dona.png",
        //     location: "",
        //     achievements: [
        //         "Developed an online platform for an NGO, integrating **Paystack** for seamless donation processing, resulting in a **40% increase in donations** within the first 3 months.",
        //     ],
        //     dates: "",
        //     link: "https://www.donacarefoundation.org",
        // },
        {
            title: "Open Source Contributor",
            company: "Solana Foundation",
            image: "/solana.jpg",
            location: "",
            dates: "11/09/2024",
            achievements: [
                "Enhanced escrow and token swap examples using the **Steel** framework and **Rust**, with testing implemented via **Solana** bankrun.js and native **Rust**, improving code reliability by **25%**.",
                "Improved documentation for Solana Oracles, reducing developer onboarding time by **30%**.",
            ],
            link: "https://github.com/Ovodo/program-examples/tree/tokens/escrow/steel/tokens/escrow/steel",
        },
    ],
};
